# ISA Course - Project assignment (Network applications and network administration)
# Makefile
# author Jan Matufka <xmatuf00@stud.fit.vutbr.cz>

CC = g++
CFLAGS = -std=c++11 -Wall -Wextra -pedantic -g
all:
	$(CC) $(CFLAGS) message.cpp argparse.cpp main.cpp -o client